### ISSUE TITLE
-patches rebase adds all rebased commits to %changelog

### ISSUE THREAD

**Issue by ktdreyer** [openstack-packages/rdopkg#100]
I'm using the latest master (4dd0bef9b99a409ff59055a48526b31e778019ef) and noticed a behavior change from 0.42.

If I rebase my `-patches` branch (for example, to add a `DROP-IN-RPM` line to a commit), then the commits after the commit I edited will have new sha1s.

The next time I run `rdopkg patch`, rdopkg will treat all the commits after my rebase as new commits. It will add all the commit subjects to the `%changelog` simply because the sha1s changed. I have to go back into the %changelog and edit out the commits that were only rebased.

**Comment by yac** [comment]
OK that sucks. Any idea on howto detect new patches vs. old rebased ones? Using commit message instead of hash comes to mind, but that doesn't sound very bulletproof. As a fallback I can restore previous functionality or put this auto-changelog generation on an option and disable by default.

Either way, `0.43` is postponed until this is resolved. Thanks for report!

**Comment by ktdreyer** [comment]
Discussed in IRC, I was playing around with checking the patch titles @ https://github.com/ktdreyer/rdopkg/tree/wip-patches-check-subjects

**Comment by yac** [comment]
Please test my solution under review: https://review.rdoproject.org/r/#/c/5491/
