### ISSUE TITLE
rdopkg patch fails with "%{?milestone}" in release

### ISSUE THREAD

**Issue by voyageur** [openstack-packages/rdopkg#80]
Trying 0.40 on openstack-neutron.spec:

```
  %global milestone %{?milestone}
  %global release_name kilo
  %global service neutron

  %{!?upstream_version: %global upstream_version %{version}%{?milestone}}

  Name:       openstack-%{service}
  Version:    2015.1.4
  Release:    6%{?milestone}%{?dist}
```

rdopkg patch will end in:
No new patches detected in rhos/rhos-7.0-patches.

After some digging, I found that the git log command fails, as it gets "2015.1.4%{?milestone}" for from_revision

May be similar to #79

**Comment by yac** [comment]
Should be fixed in `0.41.3` along with #79. Please reopen if the problem still persists.

**Comment by bregman-arie** [comment]
We still have issue. From our CI (sorry for the format):

19:09:36 TASK [patch_rpm : Apply patch(es) on dist-git repo and bump release] ***********
19:09:39 fatal: [neutron-1325-1478977478-dsvm-functional-tester-1]: FAILED! => {"changed": true, "cmd": "git config --global user.name patchy; git config --global user.email patchy@patch.com; rdopkg patch;", "delta": "0:00:01.202622", "end": "2016-11-12 14:09:38.980217", "failed": true, "rc": 1, "start": "2016-11-12 14:09:37.777595", "stderr": "## get_package_env\nRHOS package detected.\n## ensure_patches_branch\n## get_patches_branch\ngit update-ref refs/heads/rhos-7.0-patches refs/remotes/patches/rhos-7.0-patches\n## check_new_patches\ncommand failed: git log --format=%h%x1f%s%x1f%b%x1e 2015.1.4%{?milestone}..patches/rhos-7.0-patches\nstderr:\nfatal: ambiguous argument '2015.1.4%{?milestone}..patches/rhos-7.0-patches': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\nNo new patches detected in patches/rhos-7.0-patches.\nTraceback (most recent call last):\n  File \"/usr/bin/rdopkg\", line 9, in <module>\n    load_entry_point('rdopkg==0.41.4', 'console_scripts', 'rdopkg')()\n  File \"/usr/lib/python2.7/site-packages/rdopkg/cli.py\", line 46, in main\n    sys.exit(rdopkg(*cargs))\n  File \"/usr/lib/python2.7/site-packages/rdopkg/cli.py\", line 38, in rdopkg\n    return shell.run(runner, cargs=cargs, version=VERSION)\n  File \"/usr/lib/python2.7/site-packages/rdopkg/shell.py\", line 84, in run\n    action_runner.engage()\n  File \"/usr/lib/python2.7/site-packages/rdopkg/core.py\", line 194, in engage\n    new_args = self.action_manager.run_action(step, self.args)\n  File \"/usr/lib/python2.7/site-packages/rdopkg/action.py\", line 208, in run_action\n    return action_fun(*fun_args)\n  File \"/usr/lib/python2.7/site-packages/rdopkg/actions/distgit/actions.py\", line 523, in check_new_patches\n    helpers.confirm(\"Do you want to continue anyway?\", default_yes=False)\n  File \"/usr/lib/python2.7/site-packages/rdopkg/helpers.py\", line 17, in confirm\n    i = raw_input(log.term.important(\"%s %s \" % (msg, options))).lower()\nEOFError: EOF when reading a line", "stdout": "\nDo you want to continue anyway? [Ny] ", "stdout_lines": ["", "Do you want to continue anyway? [Ny] "], "warnings": ["Consider using git module rather than running git"]}

**Comment by yac** [comment]
for `0.41.4`, you need to manually remove the recursive %{?milestone} definition. `0.42` will include a patch to automatically correct the line:

https://github.com/openstack-packages/rdopkg/commit/de45fad28d167034260ec4d477f62a6efee29020
