### ISSUE TITLE
Patches and patches_base should be before BuildArch

### ISSUE THREAD

**Issue by yazug** [openstack-packages/rdopkg#88]
It would be nice if rdopkg helped enforce making sure patches_base and patches are after SourceX and before BuildArch.

openstack-tripleo newton-rdo branch had an instance of this

https://review.rdoproject.org/r/#/c/3757/

**Comment by yazug** [comment]
Expected behavior

rdopkg update-patches/patch

`
 Source0:          https://github.com/openstack/%{repo_name}/archive/%{commit}.tar.gz#/%{repo_name}-%{commit}.tar.gz
 Source1:          tripleo
 BuildArch:        noarch

 #
 # patches_base=c3fb309727671130a32b4c19de48ec22c8530aa1
 #
 Patch0001:             0001-Use-packaged-template-directory-path.patch
`

would get turned into the following:

`
 Source0:          https://github.com/openstack/%{repo_name}/archive/%{commit}.tar.gz#/%{repo_name}-%{commit}.tar.gz
 Source1:          tripleo
 
 #
 # patches_base=c3fb309727671130a32b4c19de48ec22c8530aa1
 #
 Patch0001:             0001-Use-packaged-template-directory-path.patch
 
 BuildArch:        noarch
`

**Comment by mburns72h** [comment]
The problem (since I don't see it listed here) is that when using %autosetup, the patches do not get auto-applied during the rpm builds unless the patches appear before the buildarch in the spec file.

**Comment by yac** [comment]
`rdopkg` already contains a check for BuildArch after patches, but it was only performed when applying patches by git, not by %autosetup. Following review fixes that:

https://review.rdoproject.org/r/#/c/3762/

Instead of doing such a interusive edit, rdopkg update-patches and derived actions will refuse to work on .spec with message explaining the situation.

**Comment by yazug** [comment]
perfect solution, thanks!
