### ISSUE TITLE
Add flag to run 'rdopkg patch' even if no new patches introduced

### ISSUE THREAD

**Issue by bregman-arie** [openstack-packages/rdopkg#90]
Needed for our CI, to run automatically, without asking questions :)

**Comment by yac** [comment]
Indeed, same as non-interactive `new-version` suggested by @hguemar: https://review.rdoproject.org/r/#/c/2406/

**Comment by yac** [comment]
What should happen when distgit is already up to date with patches branch? Usually, that means you already have the latest package built so there is no reason to run `rdopkg patch` and bump version.

Maybe just end with "No new patches detcted." like `update-patches` instead of mostly useless question to proceed anyway?

**Comment by bregman-arie** [comment]
I have no problem with the question "proceed anyway?" as long as I have some flag to answer yes. Like 'rdopkg patch -f/--force'  or 'rdopkg patch -y/--yes', but I'm also k with what you proposing :+1:

**Comment by yac** [comment]
I'd rather change behavior to cover all cases without new flags if possible and this makes sense for non-interactive use while also being consistent with `update-patches`.

Note that #81 must be also fixed before this is useful.

**Comment by bregman-arie** [comment]
:+1:
